.MODEL SMALL
.STACK 100
.DATA
 ;REGISTERPAGES DB "Welcome to register pages"
 CW              DB "CAIWEN" 
 YQ              DB "YIQING" 
 F_PASSWORD      DB "CnG#8086"
 R_TEXT1         DB 13,10,13,10,"Please key in your founder username and boss password"
                 DB 13,10,"PLEASE KEY IN FOUNDER USER NAME: $"
 R_I_PW          DB 13,10,"PLEASE KEY IN FOUNDER PASSWORD:  $"
 INAME           DB 6 DUP(0)
 IPW             DB 8 DUP(0)
 R_ERROR         DB 13,10,13,10,"Your username did not match with our founder username ^-^$"
 R_PW_ERROR      DB 13,10,13,10,"Your password did not match with our founder password ^-^$"
 R_SUCESSFULL    DB 13,10,"Your login is sucessfully.$"

.CODE 
MAIN PROC
 MOV AX,@DATA 
 MOV DS,AX
LOGINUSER:
;PROMPT INPUT MESSAGE FOR USERNAME
MOV AH,09H
LEA DX,R_TEXT1
INT 21H

;GET USER INPUT (LOOP)
 MOV CX,6
 MOV SI,0
GETUSERNAME:
 MOV AH,01H
 INT 21H
 MOV INAME[SI],AL
 INC SI
 LOOP GETUSERNAME

;CHECK WHETHER USERNAME SAME WITH FOUNDERNAME OR NOT
MOV SI,0
CHECK:
    CMP SI,6
    JE DONE
    JNE CHECKCW
CHECKCW:
    MOV BL,CW[SI]
    CMP BL,INAME[SI]
    JE NEXT
    JNE CHECKYQ
CHECKYQ:
    MOV BL,YQ[SI]
    CMP BL,INAME[SI]
    JE NEXT
    JNE ERROR
NEXT:
    INC SI
    JMP CHECK
ERROR:
    MOV AH,0
    MOV AH,09H
    LEA DX,R_ERROR
    INT 21H
    JMP LOGINUSER

DONE:
    MOV AH,0
    MOV AH,09H
    LEA DX,R_SUCESSFULL
    INT 21H
    JMP LOGINPW ;JUMP PASSWORD

LOGINPW:
;PROMPT INPUT MESSAGE FOR USERPASSWORD
MOV AH,09H
LEA DX,R_I_PW
INT 21H

;GET USER PASSWORD (LOOP)
 MOV CX,8
 MOV SI,0
GETUSERPW:
 MOV AH,07H
 INT 21H
 MOV IPW[SI],AL
 MOV AH,02H
 MOV DL,"*"
 INT 21H
 INC SI
 LOOP GETUSERPW
;CHECK WHETHER USER PASSWORD SAME WITH FOUNDER PASSWORD
MOV SI,0
CHECKPW:
    CMP SI,8
    JE DONEPW
    JNE CHECKFPW
CHECKFPW:
    ;MOV BX,0
    MOV BL,F_PASSWORD[SI] ;SI VERY IMPORTANT
    CMP BL,IPW[SI]
    JE NEXTPW
    JNE ERRORPW
DONEPW:
    MOV AH,0
    MOV AH,09H
    LEA DX,R_SUCESSFULL
    INT 21H
    JMP EXIT

NEXTPW:
    INC SI
    JMP CHECKPW
ERRORPW:
    MOV AH,0
    MOV AH,09H
    LEA DX,R_PW_ERROR
    INT 21H
    JMP LOGINPW

EXIT:
 MOV AH,4CH
 INT 21H
MAIN ENDP
 END MAIN