.MODEL SMALL 
.STACK 100 
.DATA 
 ;--------------------------------FOOD MENU--------------------------------;
 ;----GLOBAL VARIABLE---;
 ;NEWLINE             DB 13,10,13,10,"$"
 F_CHOOSE            DB 13,10,13,10,"PLEASE CHOOSE WHAT YOU WANT: $" ;
 F_QUANTITY          DB 13,10,13,10,"PLEASE CHOOSE YOUR QUANTITY(0-9): $" ;
 F_TOTAL             DB 13,10,13,10,"YOUR TOTAL IS $"
 ;ARRAY TO STORE FOOD SELECTION WHICH TYPE BY USER
 I_FOOD          LABEL   BYTE
 MAX_FOOD        DB       2
 ACT_FOOD        DB       ?
 FOOD            DB       2 DUP (0)
;-----------------------------------------
 ;ARRAY TO STORE QUANTITY WHICH TYPE BY USER
 I_QUANTITY      LABEL  BYTE
 MAX_QUANTITY    DB      3
 ACT_QUANTITY    DB      ?
 QUANTITY        DB      3 DUP (0)
 ;FOOD PRICE LIST AND FOOD PRICE
 FOOD_PRICE_LIST          DB 3,4,5,6,7 ;0=nasi lemak
 FOOD_PRICE               DB ?
 ;--TOTAL
 SUM                      DB ?
.CODE 
MAIN PROC 
 MOV AX,@DATA 
 MOV DS,AX 
FOODCHOOSE:
;PROMPT FOR USER INPUT FOOD CHOOSE
 MOV AH,09H
 LEA DX,F_CHOOSE    
 INT 21H
;CHECK USER INPUT
 MOV AH,0AH
 LEA DX,I_FOOD
 INT 21H

MOV SI,0 
;FIND WHICH FOOD YOU ARE CHOOSING
FOODSELECTION:
    CMP FOOD[SI],"1"
    JE NASILEMAK
    CMP FOOD[SI],"2"
    JE SANDWICH

;FIND VALUE OF FOOD PRICE
NASILEMAK:
    MOV DX,0 ; CLEAR 0
    MOV DL,FOOD_PRICE_LIST[0] ;GET THE FIRST ITEM FROM PRICE LIST
    ADD DL,30H ;DEC CONVERT TO HEX(BEFORE CALCULATION) MAYBE NEED SUB
    MOV FOOD_PRICE,DL
    ;NEWLINE
    MOV AH,02H
    MOV DL,13
    INT 21H
    MOV DL,10
    INT 21H
    ;OUTPUT PRICE
    MOV DL,FOOD_PRICE
    INT 21H
    JMP FOODQUANTITY
SANDWICH:
    MOV DX,0 ; CLEAR 0
    MOV DL,FOOD_PRICE_LIST[1]
    ADD DL,30H ;DEC CONVERT TO HEX(BEFORE CALCULATION) MAYBE NEED SUB
    MOV FOOD_PRICE,DL
    ;NEWLINE
    MOV AH,02H
    MOV DL,0DH
    INT 21H
    MOV DL,0AH
    INT 21H
    ;OUTPUT PRICE
    MOV DL,FOOD_PRICE
    INT 21H
    JMP FOODQUANTITY
FOODQUANTITY:
;PROMPT FOR USER INPUT QUANTITY
 MOV AH,09H
 LEA DX,F_QUANTITY
 INT 21H
;CHECK USER INPUT FOR QUANTITY
 MOV AH,0AH
 LEA DX,I_QUANTITY
 INT 21H

;CHECK USER INPUT HOW MANY DIGIT FOR QUANTITY
ADD ACT_QUANTITY,30H;CONVERT DEC TO HEX
CMP ACT_QUANTITY,"1"
JE SINGLE
; CMP ACT_QUANTITY,"2"
; JE DOUBLE

SINGLE:
    ;NEWLINE
    MOV AH,02H
    MOV DL,0DH
    INT 21H
    MOV DL,0AH
    INT 21H
    MOV AX,0 ;CLEAR 0
    SUB QUANTITY,30H 
    MOV AH,02H
    MOV DL,QUANTITY
    INT 21H
    JMP CALC
; DOUBLE:
;     ;NEWLINE
;     MOV AH,02H
;     MOV DL,0DH
;     INT 21H
;     MOV DL,0AH
;     INT 21H
;     MOV DL,"B"
;     INT 21H
;     JMP EXIT

MOV AH,09H
LEA DX,F_TOTAL
INT 21H
CALC:
;---CONVERT HEX TO DEC
    SUB FOOD_PRICE,30H
    SUB QUANTITY,30H
;--CLEAR AX BECOME 0
    MOV AX,0
;--MOVE Quantity BECOME MULTIPLICANT
    MOV AL,QUANTITY
;--MOVE price become multiplier
    MUL FOOD_PRICE
;--MOV RESULT TO VARIABLE
    MOV SUM,AL
    ADD SUM,30H
;--SHOW RESULT
    MOV AH,02H
    MOV DL,SUM
    INT 21H







EXIT:
 MOV AH,4CH 
 INT 21H 
MAIN ENDP
 END MAIN